# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

get_eta <- function(xP, row_idx_, beta, idx_p, idx_l) {
    .Call(`_biglasso_get_eta`, xP, row_idx_, beta, idx_p, idx_l)
}

loglik_cox <- function(xP, offset_, row_idx_, beta, idx_p, idx_l, D_dR_sets_, d_) {
    .Call(`_biglasso_loglik_cox`, xP, offset_, row_idx_, beta, idx_p, idx_l, D_dR_sets_, d_)
}

